package pe.gob.mincetur.vuce.ve.remoting.ws.entidad;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2015-10-28T08:54:15.701-05:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/", name = "VucentWS")
@XmlSeeAlso({ObjectFactory.class})
public interface VucentWS {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sincronizarTablas", targetNamespace = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/", className = "pe.gob.mincetur.vuce.ve.remoting.ws.entidad.SincronizarTablas")
    @WebMethod(action = "urn:sincronizarTablas")
    @ResponseWrapper(localName = "sincronizarTablasResponse", targetNamespace = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/", className = "pe.gob.mincetur.vuce.ve.remoting.ws.entidad.SincronizarTablasResponse")
    public int sincronizarTablas(
        @WebParam(name = "idEntidad", targetNamespace = "")
        int idEntidad,
        @WebParam(name = "xmlMensaje", targetNamespace = "")
        javax.activation.DataHandler xmlMensaje,
        @WebParam(name = "xmlTablas", targetNamespace = "")
        javax.activation.DataHandler xmlTablas
    );

    @RequestWrapper(localName = "confirmarRecepcionMensaje", targetNamespace = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/", className = "pe.gob.mincetur.vuce.ve.remoting.ws.entidad.ConfirmarRecepcionMensaje")
    @WebMethod(action = "urn:confirmarRecepcionMensaje")
    @ResponseWrapper(localName = "confirmarRecepcionMensajeResponse", targetNamespace = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/", className = "pe.gob.mincetur.vuce.ve.remoting.ws.entidad.ConfirmarRecepcionMensajeResponse")
    public void confirmarRecepcionMensaje(
        @WebParam(name = "idTransaccion", targetNamespace = "")
        int idTransaccion,
        @WebParam(name = "error", targetNamespace = "")
        int error,
        @WebParam(name = "errores", targetNamespace = "")
        java.lang.String errores
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "obtenerLiquidacionPagos", targetNamespace = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/", className = "pe.gob.mincetur.vuce.ve.remoting.ws.entidad.ObtenerLiquidacionPagos")
    @WebMethod(action = "urn:obtenerLiquidacionPagos")
    @ResponseWrapper(localName = "obtenerLiquidacionPagosResponse", targetNamespace = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/", className = "pe.gob.mincetur.vuce.ve.remoting.ws.entidad.ObtenerLiquidacionPagosResponse")
    public java.util.List<javax.activation.DataHandler> obtenerLiquidacionPagos(
        @WebParam(name = "idEntidad", targetNamespace = "")
        int idEntidad
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "obtenerTransaccionesPendientes", targetNamespace = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/", className = "pe.gob.mincetur.vuce.ve.remoting.ws.entidad.ObtenerTransaccionesPendientes")
    @WebMethod(action = "urn:obtenerTransaccionesPendientes")
    @ResponseWrapper(localName = "obtenerTransaccionesPendientesResponse", targetNamespace = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/", className = "pe.gob.mincetur.vuce.ve.remoting.ws.entidad.ObtenerTransaccionesPendientesResponse")
    public java.util.List<javax.activation.DataHandler> obtenerTransaccionesPendientes(
        @WebParam(name = "idEntidad", targetNamespace = "")
        java.lang.Integer idEntidad
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "obtenerResultadoSincronizacionTablas", targetNamespace = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/", className = "pe.gob.mincetur.vuce.ve.remoting.ws.entidad.ObtenerResultadoSincronizacionTablas")
    @WebMethod(action = "urn:obtenerResultadoSincronizacionTablas")
    @ResponseWrapper(localName = "obtenerResultadoSincronizacionTablasResponse", targetNamespace = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/", className = "pe.gob.mincetur.vuce.ve.remoting.ws.entidad.ObtenerResultadoSincronizacionTablasResponse")
    public javax.activation.DataHandler obtenerResultadoSincronizacionTablas(
        @WebParam(name = "idEntidad", targetNamespace = "")
        int idEntidad,
        @WebParam(name = "idProcesoSincronizacion", targetNamespace = "")
        int idProcesoSincronizacion
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "obtenerTransaccionesPendientesConLimite", targetNamespace = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/", className = "pe.gob.mincetur.vuce.ve.remoting.ws.entidad.ObtenerTransaccionesPendientesConLimite")
    @WebMethod(action = "urn:obtenerTransaccionesPendientesConLimite")
    @ResponseWrapper(localName = "obtenerTransaccionesPendientesConLimiteResponse", targetNamespace = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/", className = "pe.gob.mincetur.vuce.ve.remoting.ws.entidad.ObtenerTransaccionesPendientesConLimiteResponse")
    public java.util.List<javax.activation.DataHandler> obtenerTransaccionesPendientesConLimite(
        @WebParam(name = "idEntidad", targetNamespace = "")
        java.lang.Integer idEntidad,
        @WebParam(name = "tipoTransacciones", targetNamespace = "")
        java.util.List<java.lang.String> tipoTransacciones,
        @WebParam(name = "limite", targetNamespace = "")
        java.lang.Integer limite
    );

    @RequestWrapper(localName = "enviarNotificaciones", targetNamespace = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/", className = "pe.gob.mincetur.vuce.ve.remoting.ws.entidad.EnviarNotificaciones")
    @WebMethod(action = "urn:enviarNotificaciones")
    @ResponseWrapper(localName = "enviarNotificacionesResponse", targetNamespace = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/", className = "pe.gob.mincetur.vuce.ve.remoting.ws.entidad.EnviarNotificacionesResponse")
    public void enviarNotificaciones(
        @WebParam(name = "xmlNotificacion", targetNamespace = "")
        javax.activation.DataHandler xmlNotificacion,
        @WebParam(name = "ebXML", targetNamespace = "")
        javax.activation.DataHandler ebXML,
        @WebParam(name = "adjuntos", targetNamespace = "")
        javax.activation.DataHandler adjuntos
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "obtenerErroresEnvioTransmisiones", targetNamespace = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/", className = "pe.gob.mincetur.vuce.ve.remoting.ws.entidad.ObtenerErroresEnvioTransmisiones")
    @WebMethod(action = "urn:obtenerErroresEnvioTransmisiones")
    @ResponseWrapper(localName = "obtenerErroresEnvioTransmisionesResponse", targetNamespace = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/", className = "pe.gob.mincetur.vuce.ve.remoting.ws.entidad.ObtenerErroresEnvioTransmisionesResponse")
    public java.util.List<javax.activation.DataHandler> obtenerErroresEnvioTransmisiones(
        @WebParam(name = "idEntidad", targetNamespace = "")
        int idEntidad
    );
}
