
package pe.gob.mincetur.vuce.ve.remoting.ws.entidad;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2015-10-28T08:54:15.595-05:00
 * Generated source version: 2.7.0
 * 
 */
public final class VucentWS_VucentWSImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/", "VucentWSImplService");

    private VucentWS_VucentWSImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = VucentWSImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        VucentWSImplService ss = new VucentWSImplService(wsdlURL, SERVICE_NAME);
        VucentWS port = ss.getVucentWSImplPort();  
        
        {
        System.out.println("Invoking sincronizarTablas...");
        int _sincronizarTablas_idEntidad = -1685941335;
        javax.activation.DataHandler _sincronizarTablas_xmlMensaje = null;
        javax.activation.DataHandler _sincronizarTablas_xmlTablas = null;
        int _sincronizarTablas__return = port.sincronizarTablas(_sincronizarTablas_idEntidad, _sincronizarTablas_xmlMensaje, _sincronizarTablas_xmlTablas);
        System.out.println("sincronizarTablas.result=" + _sincronizarTablas__return);


        }
        {
        System.out.println("Invoking confirmarRecepcionMensaje...");
        int _confirmarRecepcionMensaje_idTransaccion = 1599556627;
        int _confirmarRecepcionMensaje_error = -184174137;
        java.lang.String _confirmarRecepcionMensaje_errores = "_confirmarRecepcionMensaje_errores-1107548375";
        port.confirmarRecepcionMensaje(_confirmarRecepcionMensaje_idTransaccion, _confirmarRecepcionMensaje_error, _confirmarRecepcionMensaje_errores);


        }
        {
        System.out.println("Invoking obtenerLiquidacionPagos...");
        int _obtenerLiquidacionPagos_idEntidad = -1782681659;
        java.util.List<javax.activation.DataHandler> _obtenerLiquidacionPagos__return = port.obtenerLiquidacionPagos(_obtenerLiquidacionPagos_idEntidad);
        System.out.println("obtenerLiquidacionPagos.result=" + _obtenerLiquidacionPagos__return);


        }
        {
        System.out.println("Invoking obtenerTransaccionesPendientes...");
        java.lang.Integer _obtenerTransaccionesPendientes_idEntidad = Integer.valueOf(-1910156938);
        java.util.List<javax.activation.DataHandler> _obtenerTransaccionesPendientes__return = port.obtenerTransaccionesPendientes(_obtenerTransaccionesPendientes_idEntidad);
        System.out.println("obtenerTransaccionesPendientes.result=" + _obtenerTransaccionesPendientes__return);


        }
        {
        System.out.println("Invoking obtenerResultadoSincronizacionTablas...");
        int _obtenerResultadoSincronizacionTablas_idEntidad = 840485476;
        int _obtenerResultadoSincronizacionTablas_idProcesoSincronizacion = 197109554;
        javax.activation.DataHandler _obtenerResultadoSincronizacionTablas__return = port.obtenerResultadoSincronizacionTablas(_obtenerResultadoSincronizacionTablas_idEntidad, _obtenerResultadoSincronizacionTablas_idProcesoSincronizacion);
        System.out.println("obtenerResultadoSincronizacionTablas.result=" + _obtenerResultadoSincronizacionTablas__return);


        }
        {
        System.out.println("Invoking obtenerTransaccionesPendientesConLimite...");
        java.lang.Integer _obtenerTransaccionesPendientesConLimite_idEntidad = Integer.valueOf(-867237141);
        java.util.List<java.lang.String> _obtenerTransaccionesPendientesConLimite_tipoTransacciones = new java.util.ArrayList<java.lang.String>();
        java.lang.String _obtenerTransaccionesPendientesConLimite_tipoTransaccionesVal1 = "_obtenerTransaccionesPendientesConLimite_tipoTransaccionesVal-652340113";
        _obtenerTransaccionesPendientesConLimite_tipoTransacciones.add(_obtenerTransaccionesPendientesConLimite_tipoTransaccionesVal1);
        java.lang.Integer _obtenerTransaccionesPendientesConLimite_limite = Integer.valueOf(-327611468);
        java.util.List<javax.activation.DataHandler> _obtenerTransaccionesPendientesConLimite__return = port.obtenerTransaccionesPendientesConLimite(_obtenerTransaccionesPendientesConLimite_idEntidad, _obtenerTransaccionesPendientesConLimite_tipoTransacciones, _obtenerTransaccionesPendientesConLimite_limite);
        System.out.println("obtenerTransaccionesPendientesConLimite.result=" + _obtenerTransaccionesPendientesConLimite__return);


        }
        {
        System.out.println("Invoking enviarNotificaciones...");
        javax.activation.DataHandler _enviarNotificaciones_xmlNotificacion = null;
        javax.activation.DataHandler _enviarNotificaciones_ebXML = null;
        javax.activation.DataHandler _enviarNotificaciones_adjuntos = null;
        port.enviarNotificaciones(_enviarNotificaciones_xmlNotificacion, _enviarNotificaciones_ebXML, _enviarNotificaciones_adjuntos);


        }
        {
        System.out.println("Invoking obtenerErroresEnvioTransmisiones...");
        int _obtenerErroresEnvioTransmisiones_idEntidad = -789831691;
        java.util.List<javax.activation.DataHandler> _obtenerErroresEnvioTransmisiones__return = port.obtenerErroresEnvioTransmisiones(_obtenerErroresEnvioTransmisiones_idEntidad);
        System.out.println("obtenerErroresEnvioTransmisiones.result=" + _obtenerErroresEnvioTransmisiones__return);


        }

        System.exit(0);
    }

}
