package pe.gob.mincetur.vuce.ve.remoting.ws.entidad;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

import pe.gob.senasa.vucews.security.handler.HeaderHandlerResolver;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2015-10-28T08:54:15.718-05:00
 * Generated source version: 2.7.0
 * 
 */
@WebServiceClient(name = "VucentWSImplService", 
                  wsdlLocation = "http://20.6.7.10/vucent/services/VucentWS?wsdl",
                  targetNamespace = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/") 
public class VucentWSImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/", "VucentWSImplService");
    public final static QName VucentWSImplPort = new QName("http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/", "VucentWSImplPort");
    static {
        URL url = null;
        try {
            //url = new URL("http://20.6.7.10/vucent/services/VucentWS?wsdl");
        	url = pe.gob.mincetur.vuce.ve.remoting.ws.entidad.VucentWSImplService.class.getResource("/META-INF/wsdl/VucentWS.wsdl");
        	if (url == null) throw new MalformedURLException("/META-INF/wsdl/VucentWS.wsdl does not exist in the module.");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(VucentWSImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://200.62.224.217/vucent/services/VucentWS?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public VucentWSImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
        this.setHandlerResolver(new HeaderHandlerResolver());
    }

    public VucentWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
        this.setHandlerResolver(new HeaderHandlerResolver());
    }

    public VucentWSImplService() {
        super(WSDL_LOCATION, SERVICE);
        this.setHandlerResolver(new HeaderHandlerResolver());
    }
    

    /**
     *
     * @return
     *     returns VucentWS
     */
    @WebEndpoint(name = "VucentWSImplPort")
    public VucentWS getVucentWSImplPort() {
        return super.getPort(VucentWSImplPort, VucentWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VucentWS
     */
    @WebEndpoint(name = "VucentWSImplPort")
    public VucentWS getVucentWSImplPort(WebServiceFeature... features) {
        return super.getPort(VucentWSImplPort, VucentWS.class, features);
    }

}
