
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package pe.gob.mincetur.vuce.ve.remoting.ws.entidad;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2015-10-28T08:54:15.678-05:00
 * Generated source version: 2.7.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "VucentWSImplService",
                      portName = "VucentWSImplPort",
                      targetNamespace = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/",
                      wsdlLocation = "http://20.6.7.10/vucent/services/VucentWS?wsdl",
                      endpointInterface = "pe.gob.mincetur.vuce.ve.remoting.ws.entidad.VucentWS")
                      
public class VucentWSImpl implements VucentWS {

    private static final Logger LOG = Logger.getLogger(VucentWSImpl.class.getName());

    /* (non-Javadoc)
     * @see pe.gob.mincetur.vuce.ve.remoting.ws.entidad.VucentWS#sincronizarTablas(int  idEntidad ,)javax.activation.DataHandler  xmlMensaje ,)javax.activation.DataHandler  xmlTablas )*
     */
    public int sincronizarTablas(int idEntidad,javax.activation.DataHandler xmlMensaje,javax.activation.DataHandler xmlTablas) { 
        LOG.info("Executing operation sincronizarTablas");
        System.out.println(idEntidad);
        System.out.println(xmlMensaje);
        System.out.println(xmlTablas);
        try {
            int _return = 707395918;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see pe.gob.mincetur.vuce.ve.remoting.ws.entidad.VucentWS#confirmarRecepcionMensaje(int  idTransaccion ,)int  error ,)java.lang.String  errores )*
     */
    public void confirmarRecepcionMensaje(int idTransaccion,int error,java.lang.String errores) { 
        LOG.info("Executing operation confirmarRecepcionMensaje");
        System.out.println(idTransaccion);
        System.out.println(error);
        System.out.println(errores);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see pe.gob.mincetur.vuce.ve.remoting.ws.entidad.VucentWS#obtenerLiquidacionPagos(int  idEntidad )*
     */
    public java.util.List<javax.activation.DataHandler> obtenerLiquidacionPagos(int idEntidad) { 
        LOG.info("Executing operation obtenerLiquidacionPagos");
        System.out.println(idEntidad);
        try {
            java.util.List<javax.activation.DataHandler> _return = new java.util.ArrayList<javax.activation.DataHandler>();
            javax.activation.DataHandler _returnVal1 = null;
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see pe.gob.mincetur.vuce.ve.remoting.ws.entidad.VucentWS#obtenerTransaccionesPendientes(java.lang.Integer  idEntidad )*
     */
    public java.util.List<javax.activation.DataHandler> obtenerTransaccionesPendientes(java.lang.Integer idEntidad) { 
        LOG.info("Executing operation obtenerTransaccionesPendientes");
        System.out.println(idEntidad);
        try {
            java.util.List<javax.activation.DataHandler> _return = new java.util.ArrayList<javax.activation.DataHandler>();
            javax.activation.DataHandler _returnVal1 = null;
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see pe.gob.mincetur.vuce.ve.remoting.ws.entidad.VucentWS#obtenerResultadoSincronizacionTablas(int  idEntidad ,)int  idProcesoSincronizacion )*
     */
    public javax.activation.DataHandler obtenerResultadoSincronizacionTablas(int idEntidad,int idProcesoSincronizacion) { 
        LOG.info("Executing operation obtenerResultadoSincronizacionTablas");
        System.out.println(idEntidad);
        System.out.println(idProcesoSincronizacion);
        try {
            javax.activation.DataHandler _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see pe.gob.mincetur.vuce.ve.remoting.ws.entidad.VucentWS#obtenerTransaccionesPendientesConLimite(java.lang.Integer  idEntidad ,)java.util.List<java.lang.String>  tipoTransacciones ,)java.lang.Integer  limite )*
     */
    public java.util.List<javax.activation.DataHandler> obtenerTransaccionesPendientesConLimite(java.lang.Integer idEntidad,java.util.List<java.lang.String> tipoTransacciones,java.lang.Integer limite) { 
        LOG.info("Executing operation obtenerTransaccionesPendientesConLimite");
        System.out.println(idEntidad);
        System.out.println(tipoTransacciones);
        System.out.println(limite);
        try {
            java.util.List<javax.activation.DataHandler> _return = new java.util.ArrayList<javax.activation.DataHandler>();
            javax.activation.DataHandler _returnVal1 = null;
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see pe.gob.mincetur.vuce.ve.remoting.ws.entidad.VucentWS#enviarNotificaciones(javax.activation.DataHandler  xmlNotificacion ,)javax.activation.DataHandler  ebXML ,)javax.activation.DataHandler  adjuntos )*
     */
    public void enviarNotificaciones(javax.activation.DataHandler xmlNotificacion,javax.activation.DataHandler ebXML,javax.activation.DataHandler adjuntos) { 
        LOG.info("Executing operation enviarNotificaciones");
        System.out.println(xmlNotificacion);
        System.out.println(ebXML);
        System.out.println(adjuntos);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see pe.gob.mincetur.vuce.ve.remoting.ws.entidad.VucentWS#obtenerErroresEnvioTransmisiones(int  idEntidad )*
     */
    public java.util.List<javax.activation.DataHandler> obtenerErroresEnvioTransmisiones(int idEntidad) { 
        LOG.info("Executing operation obtenerErroresEnvioTransmisiones");
        System.out.println(idEntidad);
        try {
            java.util.List<javax.activation.DataHandler> _return = new java.util.ArrayList<javax.activation.DataHandler>();
            javax.activation.DataHandler _returnVal1 = null;
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
