
package com.oracle.bpmn.process.bpmtupa;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IniciarSolicitudCanalVUCEPortType", targetNamespace = "http://xmlns.oracle.com/bpmn/bpmnProcess/IniciarSolicitudCanalVUCE")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IniciarSolicitudCanalVUCEPortType {


    /**
     * 
     * @param codigoServicio
     * @param idOrdenVuce
     * @param nroExpediente
     */
    @WebMethod(action = "start")
    @Oneway
    @RequestWrapper(localName = "start", targetNamespace = "http://xmlns.oracle.com/bpmn/bpmnProcess/IniciarSolicitudCanalVUCE", className = "com.oracle.bpmn.process.bpmtupa.Start")
    public void start(
        @WebParam(name = "codigoServicio", targetNamespace = "")
        String codigoServicio,
        @WebParam(name = "idOrdenVuce", targetNamespace = "")
        String idOrdenVuce,
        @WebParam(name = "nroExpediente", targetNamespace = "")
        String nroExpediente);

}
