
package com.oracle.bpmn.process.bpmtupa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IniciarSolicitudCanalVUCE.service", targetNamespace = "http://xmlns.oracle.com/bpmn/bpmnProcess/IniciarSolicitudCanalVUCE", wsdlLocation = "http://srvvldsoabpm.senasa.gob.pe:7011/soa-infra/services/BPM_SENASA/BpmTUPA/IniciarSolicitudCanalVUCE.service?WSDL")
public class IniciarSolicitudCanalVUCEService
    extends Service
{

    private final static URL INICIARSOLICITUDCANALVUCESERVICE_WSDL_LOCATION;
    private final static WebServiceException INICIARSOLICITUDCANALVUCESERVICE_EXCEPTION;
    private final static QName INICIARSOLICITUDCANALVUCESERVICE_QNAME = new QName("http://xmlns.oracle.com/bpmn/bpmnProcess/IniciarSolicitudCanalVUCE", "IniciarSolicitudCanalVUCE.service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://srvvldsoabpm.senasa.gob.pe:7011/soa-infra/services/BPM_SENASA/BpmTUPA/IniciarSolicitudCanalVUCE.service?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INICIARSOLICITUDCANALVUCESERVICE_WSDL_LOCATION = url;
        INICIARSOLICITUDCANALVUCESERVICE_EXCEPTION = e;
    }

    public IniciarSolicitudCanalVUCEService() {
        super(__getWsdlLocation(), INICIARSOLICITUDCANALVUCESERVICE_QNAME);
    }

    public IniciarSolicitudCanalVUCEService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INICIARSOLICITUDCANALVUCESERVICE_QNAME, features);
    }

    public IniciarSolicitudCanalVUCEService(URL wsdlLocation) {
        super(wsdlLocation, INICIARSOLICITUDCANALVUCESERVICE_QNAME);
    }

    public IniciarSolicitudCanalVUCEService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INICIARSOLICITUDCANALVUCESERVICE_QNAME, features);
    }

    public IniciarSolicitudCanalVUCEService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IniciarSolicitudCanalVUCEService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IniciarSolicitudCanalVUCEPortType
     */
    @WebEndpoint(name = "IniciarSolicitudCanalVUCEPort")
    public IniciarSolicitudCanalVUCEPortType getIniciarSolicitudCanalVUCEPort() {
        return super.getPort(new QName("http://xmlns.oracle.com/bpmn/bpmnProcess/IniciarSolicitudCanalVUCE", "IniciarSolicitudCanalVUCEPort"), IniciarSolicitudCanalVUCEPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IniciarSolicitudCanalVUCEPortType
     */
    @WebEndpoint(name = "IniciarSolicitudCanalVUCEPort")
    public IniciarSolicitudCanalVUCEPortType getIniciarSolicitudCanalVUCEPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/bpmn/bpmnProcess/IniciarSolicitudCanalVUCE", "IniciarSolicitudCanalVUCEPort"), IniciarSolicitudCanalVUCEPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INICIARSOLICITUDCANALVUCESERVICE_EXCEPTION!= null) {
            throw INICIARSOLICITUDCANALVUCESERVICE_EXCEPTION;
        }
        return INICIARSOLICITUDCANALVUCESERVICE_WSDL_LOCATION;
    }
    
    public void start( String codigoServicio, String nroExpediente, String idOrdenVuce) {
    	this.getIniciarSolicitudCanalVUCEPort().start(codigoServicio, idOrdenVuce, nroExpediente);
    }

}
