package com.oracle.xmlns.bpel.workflow.taskqueryservice;

/*
 * #%L
 * TUPA: Integration: BPM-Client: HW Task Query Service Client
 * %%
 * Copyright (C) 2016 SENASA
 * %%
 * This software is the confidential and proprietary information of SENASA. 
 * You shall not disclose such confidential information and shall use it only 
 * in accordance with the terms of the license agreement you entered into with 
 * SENASA.
 * #L%
 */

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-11-03T11:45:13.642-05:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskQueryService", name = "TaskQueryService")
@XmlSeeAlso({oracle.bpel.services.workflow.evidence.model.ObjectFactory.class, oracle.bpel.services.workflow.task.model.ObjectFactory.class, oracle.bpel.services.workflow.task.error.model.ObjectFactory.class, oracle.bpel.services.workflow.query.model.ObjectFactory.class, oracle.bpel.services.workflow.common.tsc.model.ObjectFactory.class, oracle.bpel.services.workflow.user.model.ObjectFactory.class, oracle.bpel.services.workflow.common.model.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TaskQueryService {

    @WebMethod
    @WebResult(name = "workflowContext", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/common", partName = "payload")
    public oracle.bpel.services.workflow.common.model.WorkflowContextType authenticate(
        @WebParam(partName = "payload", name = "credential", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/common")
        oracle.bpel.services.workflow.common.model.CredentialType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "workflowContext", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/common", partName = "payload")
    public oracle.bpel.services.workflow.common.model.WorkflowContextType refreshWorkflowContext(
        @WebParam(partName = "payload", name = "refreshWorkflowContextRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/common")
        oracle.bpel.services.workflow.common.model.WorkflowContextType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "taskExistsResponse", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskQueryService", partName = "payload")
    public boolean doesTaskExist(
        @WebParam(partName = "payload", name = "doesTaskExistRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskQueryService")
        oracle.bpel.services.workflow.query.model.CountTasksRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "taskCountResponse", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskQueryService", partName = "payload")
    public int countViewTasks(
        @WebParam(partName = "payload", name = "countViewTasksRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskQueryService")
        oracle.bpel.services.workflow.query.model.CountViewTasksRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "taskListResponse", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskQueryService", partName = "payload")
    public oracle.bpel.services.workflow.query.model.TaskListResponseType getTaskHistory(
        @WebParam(partName = "payload", name = "taskHistoryRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskQueryService")
        oracle.bpel.services.workflow.query.model.TaskHistoryRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "taskExistsResponse", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskQueryService", partName = "payload")
    public boolean doesViewTaskExist(
        @WebParam(partName = "payload", name = "doesViewTaskExistRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskQueryService")
        oracle.bpel.services.workflow.query.model.CountViewTasksRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "successResponse", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskQueryService", partName = "payload")
    public java.lang.String destroyWorkflowContext(
        @WebParam(partName = "payload", name = "workflowContext", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/common")
        oracle.bpel.services.workflow.common.model.WorkflowContextType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "aggregatedTasksResponse", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskQueryService", partName = "payload")
    public oracle.bpel.services.workflow.query.model.AggregatedTasksResponseType queryViewAggregatedTasks(
        @WebParam(partName = "payload", name = "queryViewAggregatedTasksRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskQueryService")
        oracle.bpel.services.workflow.query.model.QueryViewAggregatedTasksRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "task", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/task", partName = "payload")
    public oracle.bpel.services.workflow.task.model.Task getTaskDetailsById(
        @WebParam(partName = "payload", name = "taskDetailsByIdRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskQueryService")
        oracle.bpel.services.workflow.query.model.TaskDetailsByIdRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "getPermittedAssigneesResponse", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskQueryService", partName = "payload")
    public oracle.bpel.services.workflow.query.model.GetPermittedAssigneesResponseType getPermittedAssignees(
        @WebParam(partName = "payload", name = "getPermittedAssigneesRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskQueryService")
        oracle.bpel.services.workflow.query.model.GetPermittedAssigneesRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "taskCountResponse", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskQueryService", partName = "payload")
    public int countTasks(
        @WebParam(partName = "payload", name = "countTasksRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskQueryService")
        oracle.bpel.services.workflow.query.model.CountTasksRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "taskListResponse", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskQueryService", partName = "payload")
    public oracle.bpel.services.workflow.query.model.TaskListResponseType queryDecomposedTasks(
        @WebParam(partName = "payload", name = "queryDecomposedTasksRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskQueryService")
        oracle.bpel.services.workflow.query.model.QueryDecomposedTasksRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "getPermittedAssigneesForTasksResponse", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskQueryService", partName = "payload")
    public oracle.bpel.services.workflow.query.model.GetPermittedAssigneesForTasksResponseType getPermittedAssigneesForTasks(
        @WebParam(partName = "payload", name = "getPermittedAssigneesForTasksRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskQueryService")
        oracle.bpel.services.workflow.query.model.GetPermittedAssigneesForTasksRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "aggregatedTasksResponse", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskQueryService", partName = "payload")
    public oracle.bpel.services.workflow.query.model.AggregatedTasksResponseType queryAggregatedTasks(
        @WebParam(partName = "payload", name = "queryAggregatedTasksRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskQueryService")
        oracle.bpel.services.workflow.query.model.QueryAggregatedTasksRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "task", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/task", partName = "payload")
    public oracle.bpel.services.workflow.task.model.Task getTaskVersionDetails(
        @WebParam(partName = "payload", name = "taskVersionDetailsRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskQueryService")
        oracle.bpel.services.workflow.query.model.TaskVersionDetailsRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "workflowContext", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/common", partName = "payload")
    public oracle.bpel.services.workflow.common.model.WorkflowContextType updateWorkflowContext(
        @WebParam(partName = "payload", name = "updateWorkflowContextRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskQueryService")
        oracle.bpel.services.workflow.query.model.UpdateWorkflowContextRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "taskSequence", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskQueryService", partName = "payload")
    public oracle.bpel.services.workflow.query.model.TaskSequenceType getTaskSequence(
        @WebParam(partName = "payload", name = "getTaskSequenceRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskQueryService")
        oracle.bpel.services.workflow.query.model.GetTaskSequenceRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "taskSummaryFieldsInfoResponse", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskQueryService", partName = "payload")
    public oracle.bpel.services.workflow.query.model.SummaryFieldsInfoResponseType getSummaryFieldsInfoForTask(
        @WebParam(partName = "payload", name = "getSummaryFieldsInfoForTask", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskQueryService")
        oracle.bpel.services.workflow.query.model.SummaryFieldsInfoByTaskIdType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "task", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/task", partName = "payload")
    public oracle.bpel.services.workflow.task.model.Task getTaskDetailsByNumber(
        @WebParam(partName = "payload", name = "taskDetailsByNumberRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskQueryService")
        oracle.bpel.services.workflow.query.model.TaskDetailsByNumberRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "taskListResponse", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskQueryService", partName = "payload")
    public oracle.bpel.services.workflow.query.model.TaskListResponseType queryTasks(
        @WebParam(partName = "payload", name = "taskListRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskQueryService")
        oracle.bpel.services.workflow.query.model.TaskListRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "taskListResponse", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskQueryService", partName = "payload")
    public oracle.bpel.services.workflow.query.model.TaskListResponseType queryViewTasks(
        @WebParam(partName = "payload", name = "queryViewTasksRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskQueryService")
        oracle.bpel.services.workflow.query.model.QueryViewTasksRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "taskErrorsResponse", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskQueryService", partName = "payload")
    public oracle.bpel.services.workflow.query.model.TaskErrorsResponseType queryTaskErrors(
        @WebParam(partName = "payload", name = "queryTaskErrorsRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskQueryService")
        oracle.bpel.services.workflow.query.model.QueryTaskErrorsRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "workflowContext", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/common", partName = "payload")
    public oracle.bpel.services.workflow.common.model.WorkflowContextType getWorkflowContext(
        @WebParam(partName = "payload", name = "workflowContextRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskQueryService")
        oracle.bpel.services.workflow.query.model.WorkflowContextRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "workflowContext", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/common", partName = "payload")
    public oracle.bpel.services.workflow.common.model.WorkflowContextType authenticateOnBehalfOf(
        @WebParam(partName = "payload", name = "credentialOnBehalfOfRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskQueryService")
        oracle.bpel.services.workflow.query.model.CredentialOnBehalfOfRequestType payload
    ) throws WorkflowErrorMessage;
}
