
package com.oracle.xmlns.bpel.workflow.taskqueryservice;

/*
 * #%L
 * TUPA: Integration: BPM-Client: HW Task Query Service Client
 * %%
 * Copyright (C) 2016 SENASA
 * %%
 * This software is the confidential and proprietary information of SENASA. 
 * You shall not disclose such confidential information and shall use it only 
 * in accordance with the terms of the license agreement you entered into with 
 * SENASA.
 * #L%
 */

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-11-03T11:45:13.639-05:00
 * Generated source version: 3.1.8
 */

@WebFault(name = "taskQueryServiceFaultResponse", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskQueryService")
public class WorkflowErrorMessage extends Exception {
    
    private oracle.bpel.services.workflow.query.model.TaskQueryServiceFaultType taskQueryServiceFaultResponse;

    public WorkflowErrorMessage() {
        super();
    }
    
    public WorkflowErrorMessage(String message) {
        super(message);
    }
    
    public WorkflowErrorMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public WorkflowErrorMessage(String message, oracle.bpel.services.workflow.query.model.TaskQueryServiceFaultType taskQueryServiceFaultResponse) {
        super(message);
        this.taskQueryServiceFaultResponse = taskQueryServiceFaultResponse;
    }

    public WorkflowErrorMessage(String message, oracle.bpel.services.workflow.query.model.TaskQueryServiceFaultType taskQueryServiceFaultResponse, Throwable cause) {
        super(message, cause);
        this.taskQueryServiceFaultResponse = taskQueryServiceFaultResponse;
    }

    public oracle.bpel.services.workflow.query.model.TaskQueryServiceFaultType getFaultInfo() {
        return this.taskQueryServiceFaultResponse;
    }
}
