<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://expediente.ws.senasa.gob.pe" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:tns="http://soa.senasa.gob.pe/service/ORG/procedimiento/proceso_procedimiento_tupa-v1.0" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/ExpedientePort_xsd_1.xsd"/>
            <oracle-xsl-mapper:rootElement name="obtenerExpedienteTupaResponse" namespace="http://expediente.ws.senasa.gob.pe"/>
            <oracle-xsl-mapper:param name="obtenerExpedienteTupaResponse"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/ProcesoProcedimientoTUPA.xsd"/>
            <oracle-xsl-mapper:rootElement name="procedimiento" namespace="http://soa.senasa.gob.pe/service/ORG/procedimiento/proceso_procedimiento_tupa-v1.0"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [MON JUN 03 21:01:58 COT 2024].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:procedimiento>
         <tns:codigoCentroTramite>
            <xsl:value-of select="/ns0:obtenerExpedienteTupaResponse/return/codigoCentroTramite"/>
         </tns:codigoCentroTramite>
         <tns:codigoProcedimiento>
            <xsl:value-of select="/ns0:obtenerExpedienteTupaResponse/return/codigoProcedimientoTupa"/>
         </tns:codigoProcedimiento>
         <xsl:choose>
            <xsl:when test="/ns0:obtenerExpedienteTupaResponse/return/canal != &quot;VUCE&quot;">
                <tns:canal>0</tns:canal>
            </xsl:when>
            <xsl:when test="/ns0:obtenerExpedienteTupaResponse/return/canal = &quot;VUCE&quot;">
               <tns:canal>1</tns:canal>
            </xsl:when>
         </xsl:choose>
         <tns:idSolicitante>
            <xsl:value-of select="/ns0:obtenerExpedienteTupaResponse/return/idPersona"/>
         </tns:idSolicitante>
         <tns:codigoServicio>
            <xsl:value-of select="/ns0:obtenerExpedienteTupaResponse/return/codigoServicio"/>
         </tns:codigoServicio>
         <tns:ordenVuce>
            <xsl:value-of select="/ns0:obtenerExpedienteTupaResponse/return/ordenVuce"/>
         </tns:ordenVuce>
      </tns:procedimiento>
   </xsl:template>
</xsl:stylesheet>
