package pe.gob.senasa.ws.gestiondocumento;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 101221.1153.15811)

@WebService(wsdlLocation="http://10.0.0.36/GestionDocumentoWS/GestionDocumentoWSPort?WSDL",
  targetNamespace="http://gestiondocumento.ws.senasa.gob.pe", name="GestionDocumentoWS")
@XmlSeeAlso(
  { ObjectFactory.class })
public interface GestionDocumentoWS
{
  @WebMethod
  @Action(input="http://gestiondocumento.ws.senasa.gob.pe/GestionDocumentoWS/registrarDocumentoServidorRequest",
    output="http://gestiondocumento.ws.senasa.gob.pe/GestionDocumentoWS/registrarDocumentoServidorResponse")
  @ResponseWrapper(localName="registrarDocumentoServidorResponse",
    targetNamespace="http://gestiondocumento.ws.senasa.gob.pe", className="pe.gob.senasa.ws.gestiondocumento.RegistrarDocumentoServidorResponse")
  @RequestWrapper(localName="registrarDocumentoServidor", targetNamespace="http://gestiondocumento.ws.senasa.gob.pe",
    className="pe.gob.senasa.ws.gestiondocumento.RegistrarDocumentoServidor")
  @WebResult(targetNamespace="")
  public String registrarDocumentoServidor(@WebParam(targetNamespace="",
      name="arg0")
    String arg0, @WebParam(targetNamespace="", name="arg1")
    String arg1, @WebParam(targetNamespace="", name="arg2")
    String arg2, @WebParam(targetNamespace="", name="arg3")
    String arg3, @WebParam(targetNamespace="", name="arg4")
    String arg4, @WebParam(targetNamespace="", name="arg5")
    String arg5, @WebParam(targetNamespace="", name="arg6")
    String arg6, @WebParam(targetNamespace="", name="arg7")
    List<Propiedad> arg7);

  @WebMethod
  @Action(input="http://gestiondocumento.ws.senasa.gob.pe/GestionDocumentoWS/registrarDocumentoRequest",
    output="http://gestiondocumento.ws.senasa.gob.pe/GestionDocumentoWS/registrarDocumentoResponse")
  @ResponseWrapper(localName="registrarDocumentoResponse",
    targetNamespace="http://gestiondocumento.ws.senasa.gob.pe", className="pe.gob.senasa.ws.gestiondocumento.RegistrarDocumentoResponse")
  @RequestWrapper(localName="registrarDocumento", targetNamespace="http://gestiondocumento.ws.senasa.gob.pe",
    className="pe.gob.senasa.ws.gestiondocumento.RegistrarDocumento")
  @WebResult(targetNamespace="")
  public String registrarDocumento(@WebParam(targetNamespace="", name="arg0")
    String arg0, @WebParam(targetNamespace="", name="arg1")
    String arg1, @WebParam(targetNamespace="", name="arg2")
    String arg2, @WebParam(targetNamespace="", name="arg3")
    String arg3, @WebParam(targetNamespace="", name="arg4")
    String arg4, @WebParam(targetNamespace="", name="arg5")
    String arg5, @WebParam(targetNamespace="", name="arg6")
    String arg6, @WebParam(targetNamespace="", name="arg7")
    byte[] arg7, @WebParam(targetNamespace="", name="arg8")
    List<Propiedad> arg8);

  @WebMethod
  @Action(input="http://gestiondocumento.ws.senasa.gob.pe/GestionDocumentoWS/obtenerURLRequest",
    output="http://gestiondocumento.ws.senasa.gob.pe/GestionDocumentoWS/obtenerURLResponse")
  @ResponseWrapper(localName="obtenerURLResponse", targetNamespace="http://gestiondocumento.ws.senasa.gob.pe",
    className="pe.gob.senasa.ws.gestiondocumento.ObtenerURLResponse")
  @RequestWrapper(localName="obtenerURL", targetNamespace="http://gestiondocumento.ws.senasa.gob.pe",
    className="pe.gob.senasa.ws.gestiondocumento.ObtenerURL")
  @WebResult(targetNamespace="")
  public String obtenerURL(@WebParam(targetNamespace="", name="arg0")
    String arg0);

  @WebMethod
  @Action(input="http://gestiondocumento.ws.senasa.gob.pe/GestionDocumentoWS/obtenerDocumentoRequest",
    output="http://gestiondocumento.ws.senasa.gob.pe/GestionDocumentoWS/obtenerDocumentoResponse")
  @ResponseWrapper(localName="obtenerDocumentoResponse", targetNamespace="http://gestiondocumento.ws.senasa.gob.pe",
    className="pe.gob.senasa.ws.gestiondocumento.ObtenerDocumentoResponse")
  @RequestWrapper(localName="obtenerDocumento", targetNamespace="http://gestiondocumento.ws.senasa.gob.pe",
    className="pe.gob.senasa.ws.gestiondocumento.ObtenerDocumento")
  @WebResult(targetNamespace="")
  public byte[] obtenerDocumento(@WebParam(targetNamespace="", name="arg0")
    String arg0);
}
