package com.oracle.xmlns.bpel.workflow.runtimeconfig;

/*
 * #%L
 * TUPA: Integration: BPM-Client: HW Runtime Service Client
 * %%
 * Copyright (C) 2016 SENASA
 * %%
 * This software is the confidential and proprietary information of SENASA. 
 * You shall not disclose such confidential information and shall use it only 
 * in accordance with the terms of the license agreement you entered into with 
 * SENASA.
 * #L%
 */

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-11-03T12:49:27.925-05:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig", name = "runtimeConfigService")
@XmlSeeAlso({com.oracle.xmlns.bpel.workflow.translatedvalues.ObjectFactory.class, com.oracle.xmlns.pcbpel.humanworkflow.configurations.ObjectFactory.class, oracle.bpel.services.workflow.runtimeconfig.model.ObjectFactory.class, oracle.bpel.services.workflow.common.model.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RuntimeConfigService {

    @WebMethod
    @WebResult(name = "successResponse", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig", partName = "payload")
    public java.lang.String deleteAttributeLabel(
        @WebParam(partName = "payload", name = "deleteAttributeLabelRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig")
        oracle.bpel.services.workflow.runtimeconfig.model.AttributeLabelIdRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "approvalGroupNameList", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig", partName = "payload")
    public oracle.bpel.services.workflow.runtimeconfig.model.ApprovalGroupNameList searchApprovalGroups(
        @WebParam(partName = "payload", name = "searchApprovalGroupsRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig")
        oracle.bpel.services.workflow.runtimeconfig.model.ApprovalGroupSearchRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "getSupportedWorkflowExtensionsResponse", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig", partName = "payload")
    public oracle.bpel.services.workflow.runtimeconfig.model.GetSupportedWorkflowExtensionsResponseType getSupportedWorkflowExtensions(
        @WebParam(partName = "payload", name = "getSupportedWorkflowExtensionsRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig")
        java.lang.String payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "taskDisplayInfoList", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig", partName = "payload")
    public oracle.bpel.services.workflow.runtimeconfig.model.TaskDisplayInfoList getTaskDisplayInfoByTaskDefinitionId(
        @WebParam(partName = "payload", name = "getTaskDisplayInfoByTaskDefinitionIdRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig")
        oracle.bpel.services.workflow.runtimeconfig.model.GetTaskDisplayInfoByTaskDefinitionIdRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "getServerURLFromFabricConfigResponse", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig", partName = "payload")
    public java.lang.String getServerURLFromFabricConfig(
        @WebParam(partName = "payload", name = "getServerURLFromFabricConfigRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig")
        java.lang.String payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "getJndiURLFromFabricConfigResponse", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig", partName = "payload")
    public java.lang.String getJndiURLFromFabricConfig(
        @WebParam(partName = "payload", name = "getJndiURLFromFabricConfigRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig")
        java.lang.String payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "attributeLabelUsageList", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig", partName = "payload")
    public oracle.bpel.services.workflow.runtimeconfig.model.AttributeLabelUsageList getAttributeLabelUsages(
        @WebParam(partName = "payload", name = "getAttributeLabelUsagesRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig")
        oracle.bpel.services.workflow.runtimeconfig.model.AttributeTypeRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "dynamicAssignFunctionList", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig", partName = "payload")
    public oracle.bpel.services.workflow.runtimeconfig.model.DynamicAssignFunctionList getDynamicAssignmentFunctions(
        @WebParam(partName = "payload", name = "getDynamicAssignmentFunctionsRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig")
        oracle.bpel.services.workflow.runtimeconfig.model.GetDynamicAssignmentFunctionsRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "successResponse", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig", partName = "payload")
    public java.lang.String deleteTaskDisplayInfo(
        @WebParam(partName = "payload", name = "deleteTaskDisplayInfoRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig")
        oracle.bpel.services.workflow.runtimeconfig.model.DeleteTaskDisplayInfoRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "successResponse", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig", partName = "payload")
    public java.lang.String updateApprovalGroup(
        @WebParam(partName = "payload", name = "updateApprovalGroupRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig")
        oracle.bpel.services.workflow.runtimeconfig.model.ApprovalGroupRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "attributeLabel", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig", partName = "payload")
    public oracle.bpel.services.workflow.runtimeconfig.model.AttributeLabelType updateAttributeLabel(
        @WebParam(partName = "payload", name = "updateAttributeLabelRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig")
        oracle.bpel.services.workflow.runtimeconfig.model.AttributeLabelRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "payloadMapping", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig", partName = "payload")
    public oracle.bpel.services.workflow.runtimeconfig.model.PayloadMappingType createPayloadMapping(
        @WebParam(partName = "payload", name = "createPayloadMappingRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig")
        oracle.bpel.services.workflow.runtimeconfig.model.PayloadMappingRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "taskDisplayInfoList", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig", partName = "payload")
    public oracle.bpel.services.workflow.runtimeconfig.model.TaskDisplayInfoList getTaskDisplayInfo(
        @WebParam(partName = "payload", name = "getTaskDisplayInfoRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig")
        oracle.bpel.services.workflow.runtimeconfig.model.GetTaskDisplayInfoRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "workflowConfigurations", targetNamespace = "http://xmlns.oracle.com/pcbpel/humanworkflow/configurations", partName = "payload")
    public com.oracle.xmlns.pcbpel.humanworkflow.configurations.WorkflowConfigurations getConfiguration(
        @WebParam(partName = "payload", name = "getConfigurationRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig")
        oracle.bpel.services.workflow.runtimeconfig.model.WfCtxtRequestType payload
    ) throws WorkflowErrorMessage;

    /**
     * Deprecated - use getDynamicAssignmentFunctions instead
     */
    @WebMethod
    @WebResult(name = "dynamicAssignFunctionList", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig", partName = "payload")
    public oracle.bpel.services.workflow.runtimeconfig.model.DynamicAssignFunctionList getUserDynamicAssignmentFunctions(
        @WebParam(partName = "payload", name = "getUserDynamicAssignmentFunctionsRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig")
        oracle.bpel.services.workflow.runtimeconfig.model.WfCtxtRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "successResponse", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig", partName = "payload")
    public java.lang.String deleteFromGroup(
        @WebParam(partName = "payload", name = "deleteFromGroupRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig")
        oracle.bpel.services.workflow.runtimeconfig.model.ApprovalGroupMemberRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "successResponse", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig", partName = "payload")
    public java.lang.String createInGroup(
        @WebParam(partName = "payload", name = "createInGroupRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig")
        oracle.bpel.services.workflow.runtimeconfig.model.ApprovalGroupMemberRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "translatedValues", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/translatedValues", partName = "payload")
    public com.oracle.xmlns.bpel.workflow.translatedvalues.TranslatedValues getTranslatedValuesUsingTaskDefIds(
        @WebParam(partName = "payload", name = "getTranslatedValuesUsingTaskDefIdsRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig")
        oracle.bpel.services.workflow.runtimeconfig.model.GetTranslatedValuesUsingTaskDefIdsRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "successResponse", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig", partName = "payload")
    public java.lang.String setTaskDisplayInfo(
        @WebParam(partName = "payload", name = "setTaskDisplayInfoRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig")
        oracle.bpel.services.workflow.runtimeconfig.model.SetTaskDisplayInfoRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "successResponse", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig", partName = "payload")
    public java.lang.String bulkUpdateApprovalGroup(
        @WebParam(partName = "payload", name = "bulkUpdateApprovalGroupRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig")
        oracle.bpel.services.workflow.runtimeconfig.model.ApprovalGroupRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "successResponse", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig", partName = "payload")
    public java.lang.String deletePayloadMapping(
        @WebParam(partName = "payload", name = "deletePayloadMappingRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig")
        oracle.bpel.services.workflow.runtimeconfig.model.PayloadMappingRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "approvalGroup", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig", partName = "payload")
    public oracle.bpel.services.workflow.runtimeconfig.model.ApprovalGroupType getApprovalGroup(
        @WebParam(partName = "payload", name = "getApprovalGroupRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig")
        oracle.bpel.services.workflow.runtimeconfig.model.ApprovalGroupNameRequestType payload
    ) throws WorkflowErrorMessage;

    /**
     * Deprecated - use getDynamicAssignmentFunctions instead
     */
    @WebMethod
    @WebResult(name = "dynamicAssignFunctionList", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig", partName = "payload")
    public oracle.bpel.services.workflow.runtimeconfig.model.DynamicAssignFunctionList getGroupDynamicAssignmentFunctions(
        @WebParam(partName = "payload", name = "getGroupDynamicAssignmentFunctionsRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig")
        oracle.bpel.services.workflow.runtimeconfig.model.WfCtxtRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "attributeLabel", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig", partName = "payload")
    public oracle.bpel.services.workflow.runtimeconfig.model.AttributeLabelType createAttributeLabel(
        @WebParam(partName = "payload", name = "createAttributeLabelRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig")
        oracle.bpel.services.workflow.runtimeconfig.model.AttributeLabelRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "getInternalServerURLResponse", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig", partName = "payload")
    public java.lang.String getInternalServerURL(
        @WebParam(partName = "payload", name = "getInternalServerURLRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig")
        java.lang.String payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "payloadMappingsList", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig", partName = "payload")
    public oracle.bpel.services.workflow.runtimeconfig.model.PayloadMappingsList getBPMProcessPayloadMappings(
        @WebParam(partName = "payload", name = "getBPMProcessPayloadMappingsRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig")
        oracle.bpel.services.workflow.runtimeconfig.model.ProcessDNRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "taskStatus", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig", partName = "payload")
    public oracle.bpel.services.workflow.runtimeconfig.model.TaskStatusType getTaskStatus(
        @WebParam(partName = "payload", name = "getTaskStatusRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig")
        oracle.bpel.services.workflow.runtimeconfig.model.GetTaskStatusRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "successResponse", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig", partName = "payload")
    public java.lang.String updateInGroup(
        @WebParam(partName = "payload", name = "updateInGroupRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig")
        oracle.bpel.services.workflow.runtimeconfig.model.ApprovalGroupMemberRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "payloadMappingsList", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig", partName = "payload")
    public oracle.bpel.services.workflow.runtimeconfig.model.PayloadMappingsList getWorkflowPayloadMappings(
        @WebParam(partName = "payload", name = "getWorkflowPayloadMappingsRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig")
        oracle.bpel.services.workflow.runtimeconfig.model.WorkflowIdRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "successResponse", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig", partName = "payload")
    public java.lang.String deleteApprovalGroup(
        @WebParam(partName = "payload", name = "deleteApprovalGroupRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig")
        oracle.bpel.services.workflow.runtimeconfig.model.ApprovalGroupNameRequestType payload
    ) throws WorkflowErrorMessage;

    @WebMethod
    @WebResult(name = "successResponse", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig", partName = "payload")
    public java.lang.String createApprovalGroup(
        @WebParam(partName = "payload", name = "createApprovalGroupRequest", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig")
        oracle.bpel.services.workflow.runtimeconfig.model.ApprovalGroupRequestType payload
    ) throws WorkflowErrorMessage;
}
