
package com.oracle.xmlns.bpel.workflow.runtimeconfig;

/*
 * #%L
 * TUPA: Integration: BPM-Client: HW Runtime Service Client
 * %%
 * Copyright (C) 2016 SENASA
 * %%
 * This software is the confidential and proprietary information of SENASA. 
 * You shall not disclose such confidential information and shall use it only 
 * in accordance with the terms of the license agreement you entered into with 
 * SENASA.
 * #L%
 */

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-11-03T12:49:27.922-05:00
 * Generated source version: 3.1.8
 */

@WebFault(name = "fault", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/runtimeConfig")
public class WorkflowErrorMessage extends Exception {
    
    private oracle.bpel.services.workflow.runtimeconfig.model.FaultType fault;

    public WorkflowErrorMessage() {
        super();
    }
    
    public WorkflowErrorMessage(String message) {
        super(message);
    }
    
    public WorkflowErrorMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public WorkflowErrorMessage(String message, oracle.bpel.services.workflow.runtimeconfig.model.FaultType fault) {
        super(message);
        this.fault = fault;
    }

    public WorkflowErrorMessage(String message, oracle.bpel.services.workflow.runtimeconfig.model.FaultType fault, Throwable cause) {
        super(message, cause);
        this.fault = fault;
    }

    public oracle.bpel.services.workflow.runtimeconfig.model.FaultType getFaultInfo() {
        return this.fault;
    }
}
