package proxy.firma.xml;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 101221.1153.15811)

@WebService(wsdlLocation="http://bpm.senasa.gob.pe:7003/WSFirmaXMLProd/firmarxml?WSDL",
  targetNamespace="http://clases/", name="firmarxml")
@XmlSeeAlso(
  { ObjectFactory.class })
public interface Firmarxml
{
  @WebMethod
  @Action(input="http://clases/firmarxml/firmarRequest", output="http://clases/firmarxml/firmarResponse")
  @ResponseWrapper(localName="firmarResponse", targetNamespace="http://clases/",
    className="proxy.firma.xml.FirmarResponse")
  @RequestWrapper(localName="firmar", targetNamespace="http://clases/",
    className="proxy.firma.xml.Firmar")
  @WebResult(targetNamespace="")
  public byte[] firmar(@WebParam(targetNamespace="", name="certificado")
    byte[] certificado, @WebParam(targetNamespace="", name="clavecertificado")
    String clavecertificado, @WebParam(targetNamespace="", name="documento")
    byte[] documento, @WebParam(targetNamespace="", name="urltsa")
    String urltsa, @WebParam(targetNamespace="", name="usertsa")
    String usertsa, @WebParam(targetNamespace="", name="pwdtsa")
    String pwdtsa, @WebParam(targetNamespace="", name="Pucmid")
    String pucmid, @WebParam(targetNamespace="", name="PflagTipo")
    int pflagTipo);

  @WebMethod
  @Action(input="http://clases/firmarxml/obtenerRespuestaRequest", output="http://clases/firmarxml/obtenerRespuestaResponse")
  @ResponseWrapper(localName="obtenerRespuestaResponse", targetNamespace="http://clases/",
    className="proxy.firma.xml.ObtenerRespuestaResponse")
  @RequestWrapper(localName="obtenerRespuesta", targetNamespace="http://clases/",
    className="proxy.firma.xml.ObtenerRespuesta")
  @WebResult(targetNamespace="")
  public Respuesta obtenerRespuesta();
}
