package proxy.senasaws.tramite;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 101221.1153.15811)

@WebServiceClient(wsdlLocation="http://bpmdes.senasa.gob.pe:7003/senasaws/TramiteDocumentarioPort?wsdl",
  targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe", name="TramiteDocumentario")
public class TramiteDocumentario_Service
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("proxy.senasaws.tramite.TramiteDocumentario_Service");
      URL baseUrl = TramiteDocumentario_Service.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            TramiteDocumentario_Service.class.getResource("http://bpmdes.senasa.gob.pe:7003/senasaws/TramiteDocumentarioPort?wsdl");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://bpmdes.senasa.gob.pe:7003/senasaws/TramiteDocumentarioPort?wsdl");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://bpmdes.senasa.gob.pe:7003/senasaws/TramiteDocumentarioPort?wsdl");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://bpmdes.senasa.gob.pe:7003/senasaws/TramiteDocumentarioPort?wsdl",
          e);
    }
  }

  public TramiteDocumentario_Service()
  {
    super(wsdlLocationURL,
          new QName("http://tramitedocumentario.ws.senasa.gob.pe",
                    "TramiteDocumentario"));
  }

  public TramiteDocumentario_Service(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="TramiteDocumentarioPort")
  public TramiteDocumentario getTramiteDocumentarioPort()
  {
    return (TramiteDocumentario) super.getPort(new QName("http://tramitedocumentario.ws.senasa.gob.pe",
                                                         "TramiteDocumentarioPort"),
                                               TramiteDocumentario.class);
  }

  @WebEndpoint(name="TramiteDocumentarioPort")
  public TramiteDocumentario getTramiteDocumentarioPort(WebServiceFeature... features)
  {
    return (TramiteDocumentario) super.getPort(new QName("http://tramitedocumentario.ws.senasa.gob.pe",
                                                         "TramiteDocumentarioPort"),
                                               TramiteDocumentario.class,
                                               features);
  }
}
