package proxy.senasaws.tramite;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 101221.1153.15811)

@WebService(wsdlLocation="http://bpmdes.senasa.gob.pe:7003/senasaws/TramiteDocumentarioPort?wsdl",
  targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe", name="TramiteDocumentario")
@XmlSeeAlso(
  { ObjectFactory.class })
public interface TramiteDocumentario
{
  @WebMethod
  @Action(input="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/generarDocumentoTramiteRequest",
    output="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/generarDocumentoTramiteResponse")
  @ResponseWrapper(localName="generarDocumentoTramiteResponse",
    targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.GenerarDocumentoTramiteResponse")
  @RequestWrapper(localName="generarDocumentoTramite", targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.GenerarDocumentoTramite")
  @WebResult(targetNamespace="")
  public Documento generarDocumentoTramite(@WebParam(targetNamespace="",
      name="documentoFisico")
    byte[] documentoFisico, @WebParam(targetNamespace="", name="nombre")
    String nombre, @WebParam(targetNamespace="", name="documento")
    Documento documento);

  @WebMethod
  @Action(input="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/previsualizarIngresoDocTramiteRequest",
    output="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/previsualizarIngresoDocTramiteResponse")
  @ResponseWrapper(localName="previsualizarIngresoDocTramiteResponse",
    targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.PrevisualizarIngresoDocTramiteResponse")
  @RequestWrapper(localName="previsualizarIngresoDocTramite",
    targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.PrevisualizarIngresoDocTramite")
  @WebResult(targetNamespace="")
  public byte[] previsualizarIngresoDocTramite(@WebParam(targetNamespace="",
      name="arg0")
    byte[] arg0, @WebParam(targetNamespace="", name="arg1")
    String arg1, @WebParam(targetNamespace="", name="arg2")
    Documento arg2);

  @WebMethod
  @Action(input="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/eliminarNumeracioDocumentoRequest",
    output="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/eliminarNumeracioDocumentoResponse")
  @ResponseWrapper(localName="eliminarNumeracioDocumentoResponse",
    targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.EliminarNumeracioDocumentoResponse")
  @RequestWrapper(localName="eliminarNumeracioDocumento", targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.EliminarNumeracioDocumento")
  public void eliminarNumeracioDocumento(@WebParam(targetNamespace="",
      name="subTipo")
    String subTipo, @WebParam(targetNamespace="", name="area")
    String area, @WebParam(targetNamespace="", name="subArea")
    String subArea, @WebParam(targetNamespace="", name="personaId")
    String personaId);

  @WebMethod
  @Action(input="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/registrarDocumentoRequest",
    output="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/registrarDocumentoResponse")
  @ResponseWrapper(localName="registrarDocumentoResponse",
    targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.RegistrarDocumentoResponse")
  @RequestWrapper(localName="registrarDocumento", targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.RegistrarDocumento")
  @WebResult(targetNamespace="")
  public String registrarDocumento(@WebParam(targetNamespace="", name="arg0")
    DocumentoSTD arg0, @WebParam(targetNamespace="", name="arg1")
    String arg1);

  @WebMethod
  @Action(input="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/actualizarDocumentoRequest",
    output="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/actualizarDocumentoResponse")
  @ResponseWrapper(localName="actualizarDocumentoResponse",
    targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.ActualizarDocumentoResponse")
  @RequestWrapper(localName="actualizarDocumento", targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.ActualizarDocumento")
  public void actualizarDocumento(@WebParam(targetNamespace="", name="arg0")
    DocumentoSTD arg0, @WebParam(targetNamespace="", name="arg1")
    String arg1);

  @WebMethod
  @Action(input="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/actualizarArchivoRequest",
    output="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/actualizarArchivoResponse")
  @ResponseWrapper(localName="actualizarArchivoResponse", targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.ActualizarArchivoResponse")
  @RequestWrapper(localName="actualizarArchivo", targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.ActualizarArchivo")
  public void actualizarArchivo(@WebParam(targetNamespace="", name="arg0")
    DocumentoSTD arg0, @WebParam(targetNamespace="", name="arg1")
    String arg1);

  @WebMethod
  @Action(input="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/eliminarDocumentoAdjuntoRequest",
    output="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/eliminarDocumentoAdjuntoResponse")
  @ResponseWrapper(localName="eliminarDocumentoAdjuntoResponse",
    targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.EliminarDocumentoAdjuntoResponse")
  @RequestWrapper(localName="eliminarDocumentoAdjunto", targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.EliminarDocumentoAdjunto")
  public void eliminarDocumentoAdjunto(@WebParam(targetNamespace="", name="arg0")
    DocumentoSTD arg0);

  @WebMethod
  @Action(input="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/obtenerAdjuntosRequest",
    output="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/obtenerAdjuntosResponse")
  @ResponseWrapper(localName="obtenerAdjuntosResponse", targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.ObtenerAdjuntosResponse")
  @RequestWrapper(localName="obtenerAdjuntos", targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.ObtenerAdjuntos")
  @WebResult(targetNamespace="")
  public List<DocumentoSTD> obtenerAdjuntos(@WebParam(targetNamespace="",
      name="arg0")
    DocumentoSTD arg0);

  @WebMethod
  @Action(input="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/verificaParticipacionRequest",
    output="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/verificaParticipacionResponse")
  @ResponseWrapper(localName="verificaParticipacionResponse",
    targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.VerificaParticipacionResponse")
  @RequestWrapper(localName="verificaParticipacion", targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.VerificaParticipacion")
  @WebResult(targetNamespace="")
  public int verificaParticipacion(@WebParam(targetNamespace="", name="arg0")
    DocumentoSTD arg0);

  @WebMethod
  @Action(input="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/consultaSTDGeneralRequest",
    output="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/consultaSTDGeneralResponse")
  @ResponseWrapper(localName="consultaSTDGeneralResponse",
    targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.ConsultaSTDGeneralResponse")
  @RequestWrapper(localName="consultaSTDGeneral", targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.ConsultaSTDGeneral")
  @WebResult(targetNamespace="")
  public List<ReporteSTD> consultaSTDGeneral(@WebParam(targetNamespace="",
      name="arg0")
    ReporteSTD arg0);

  @WebMethod
  @Action(input="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/consultaSTDGeneralExternoRequest",
    output="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/consultaSTDGeneralExternoResponse")
  @ResponseWrapper(localName="consultaSTDGeneralExternoResponse",
    targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.ConsultaSTDGeneralExternoResponse")
  @RequestWrapper(localName="consultaSTDGeneralExterno", targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.ConsultaSTDGeneralExterno")
  @WebResult(targetNamespace="")
  public List<ReporteSTD> consultaSTDGeneralExterno(@WebParam(targetNamespace="",
      name="arg0")
    ReporteSTD arg0);

  @WebMethod
  @Action(input="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/consultaSTDDocumentosRequest",
    output="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/consultaSTDDocumentosResponse")
  @ResponseWrapper(localName="consultaSTDDocumentosResponse",
    targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.ConsultaSTDDocumentosResponse")
  @RequestWrapper(localName="consultaSTDDocumentos", targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.ConsultaSTDDocumentos")
  @WebResult(targetNamespace="")
  public List<DocumentoSTD> consultaSTDDocumentos(@WebParam(targetNamespace="",
      name="arg0")
    String arg0);

  @WebMethod
  @Action(input="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/consultaSTDxIdFinalRequest",
    output="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/consultaSTDxIdFinalResponse")
  @ResponseWrapper(localName="consultaSTDxIdFinalResponse",
    targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.ConsultaSTDxIdFinalResponse")
  @RequestWrapper(localName="consultaSTDxIdFinal", targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.ConsultaSTDxIdFinal")
  @WebResult(targetNamespace="")
  public List<ReporteSTD> consultaSTDxIdFinal(@WebParam(targetNamespace="",
      name="arg0")
    String arg0);

  @WebMethod
  @Action(input="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/obtenerEncargaturaRequest",
    output="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/obtenerEncargaturaResponse")
  @ResponseWrapper(localName="obtenerEncargaturaResponse",
    targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.ObtenerEncargaturaResponse")
  @RequestWrapper(localName="obtenerEncargatura", targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.ObtenerEncargatura")
  @WebResult(targetNamespace="")
  public List<Encargatura> obtenerEncargatura(@WebParam(targetNamespace="",
      name="arg0")
    String arg0);

  @WebMethod
  @Action(input="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/obtenerEncargadoRequest",
    output="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/obtenerEncargadoResponse")
  @ResponseWrapper(localName="obtenerEncargadoResponse", targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.ObtenerEncargadoResponse")
  @RequestWrapper(localName="obtenerEncargado", targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.ObtenerEncargado")
  @WebResult(targetNamespace="")
  public List<Encargatura> obtenerEncargado(@WebParam(targetNamespace="",
      name="arg0")
    String arg0);

  @WebMethod
  @Action(input="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/eliminarDocumentoSTDRequest",
    output="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/eliminarDocumentoSTDResponse")
  @ResponseWrapper(localName="eliminarDocumentoSTDResponse",
    targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.EliminarDocumentoSTDResponse")
  @RequestWrapper(localName="eliminarDocumentoSTD", targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.EliminarDocumentoSTD")
  @WebResult(targetNamespace="")
  public Boolean eliminarDocumentoSTD(@WebParam(targetNamespace="", name="pcodigoSTD")
    String pcodigoSTD, @WebParam(targetNamespace="", name="pIdUcm")
    String pIdUcm);

  @WebMethod
  @Action(input="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/obtenerBandejaElectronicaRequest",
    output="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/obtenerBandejaElectronicaResponse")
  @ResponseWrapper(localName="obtenerBandejaElectronicaResponse",
    targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.ObtenerBandejaElectronicaResponse")
  @RequestWrapper(localName="obtenerBandejaElectronica", targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.ObtenerBandejaElectronica")
  @WebResult(targetNamespace="")
  public List<DocumentoElectronico> obtenerBandejaElectronica();

  @WebMethod
  @Action(input="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/procesarDocumentoElectronicoRequest",
    output="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/procesarDocumentoElectronicoResponse")
  @ResponseWrapper(localName="procesarDocumentoElectronicoResponse",
    targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.ProcesarDocumentoElectronicoResponse")
  @RequestWrapper(localName="procesarDocumentoElectronico",
    targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.ProcesarDocumentoElectronico")
  public void procesarDocumentoElectronico(@WebParam(targetNamespace="",
      name="idEntidad")
    String idEntidad, @WebParam(targetNamespace="", name="idTransaccion")
    String idTransaccion, @WebParam(targetNamespace="", name="codigoDocumento")
    String codigoDocumento, @WebParam(targetNamespace="", name="accion")
    String accion, @WebParam(targetNamespace="", name="usuario")
    String usuario);

  @WebMethod
  @Action(input="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/obtenerExpedienteStdRequest",
    output="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/obtenerExpedienteStdResponse")
  @ResponseWrapper(localName="obtenerExpedienteStdResponse",
    targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.ObtenerExpedienteStdResponse")
  @RequestWrapper(localName="obtenerExpedienteStd", targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.ObtenerExpedienteStd")
  @WebResult(targetNamespace="")
  public Expediente obtenerExpedienteStd(@WebParam(targetNamespace="",
      name="arg0")
    String arg0);

  @WebMethod
  @Action(input="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/obtenerDocumentoStdRequest",
    output="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/obtenerDocumentoStdResponse")
  @ResponseWrapper(localName="obtenerDocumentoStdResponse",
    targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.ObtenerDocumentoStdResponse")
  @RequestWrapper(localName="obtenerDocumentoStd", targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.ObtenerDocumentoStd")
  @WebResult(targetNamespace="")
  public DocumentoSTD obtenerDocumentoStd(@WebParam(targetNamespace="",
      name="arg0")
    String arg0, @WebParam(targetNamespace="", name="arg1")
    String arg1);

  @WebMethod
  @Action(input="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/obtenerTiposDocMesaPartesRequest",
    output="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/obtenerTiposDocMesaPartesResponse")
  @ResponseWrapper(localName="obtenerTiposDocMesaPartesResponse",
    targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.ObtenerTiposDocMesaPartesResponse")
  @RequestWrapper(localName="obtenerTiposDocMesaPartes", targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.ObtenerTiposDocMesaPartes")
  @WebResult(targetNamespace="")
  public List<SubTipo> obtenerTiposDocMesaPartes();

  @WebMethod
  @Action(input="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/registrarExpedienteRequest",
    output="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/registrarExpedienteResponse")
  @ResponseWrapper(localName="registrarExpedienteResponse",
    targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.RegistrarExpedienteResponse")
  @RequestWrapper(localName="registrarExpediente", targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.RegistrarExpediente")
  @WebResult(targetNamespace="")
  public Expediente registrarExpediente(@WebParam(targetNamespace="",
      name="arg0")
    String arg0, @WebParam(targetNamespace="", name="arg1")
    String arg1, @WebParam(targetNamespace="", name="arg2")
    String arg2, @WebParam(targetNamespace="", name="arg3")
    String arg3);

  @WebMethod
  @Action(input="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/anexarDocumentoExpedienteRequest",
    output="http://tramitedocumentario.ws.senasa.gob.pe/TramiteDocumentario/anexarDocumentoExpedienteResponse")
  @ResponseWrapper(localName="anexarDocumentoExpedienteResponse",
    targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.AnexarDocumentoExpedienteResponse")
  @RequestWrapper(localName="anexarDocumentoExpediente", targetNamespace="http://tramitedocumentario.ws.senasa.gob.pe",
    className="proxy.senasaws.tramite.AnexarDocumentoExpediente")
  @WebResult(targetNamespace="")
  public Audit anexarDocumentoExpediente(@WebParam(targetNamespace="",
      name="arg0")
    String arg0, @WebParam(targetNamespace="", name="arg1")
    String arg1, @WebParam(targetNamespace="", name="arg2")
    String arg2);
}
