
package com.oracle.xmlns.bpel.workflow.taskservice;

/*
 * #%L
 * TUPA: Integration: BPM-Client: HW Task Service Client
 * %%
 * Copyright (C) 2016 SENASA
 * %%
 * This software is the confidential and proprietary information of SENASA. 
 * You shall not disclose such confidential information and shall use it only 
 * in accordance with the terms of the license agreement you entered into with 
 * SENASA.
 * #L%
 */

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-11-03T10:59:40.309-05:00
 * Generated source version: 3.1.8
 */

@WebFault(name = "staleObjectFault", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
public class StaleObjectFaultMessage extends Exception {
    
    private com.oracle.xmlns.bpel.workflow.taskservice.FaultMessageType staleObjectFault;

    public StaleObjectFaultMessage() {
        super();
    }
    
    public StaleObjectFaultMessage(String message) {
        super(message);
    }
    
    public StaleObjectFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public StaleObjectFaultMessage(String message, com.oracle.xmlns.bpel.workflow.taskservice.FaultMessageType staleObjectFault) {
        super(message);
        this.staleObjectFault = staleObjectFault;
    }

    public StaleObjectFaultMessage(String message, com.oracle.xmlns.bpel.workflow.taskservice.FaultMessageType staleObjectFault, Throwable cause) {
        super(message, cause);
        this.staleObjectFault = staleObjectFault;
    }

    public com.oracle.xmlns.bpel.workflow.taskservice.FaultMessageType getFaultInfo() {
        return this.staleObjectFault;
    }
}
