package com.oracle.xmlns.bpel.workflow.taskservice;

/*
 * #%L
 * TUPA: Integration: BPM-Client: HW Task Service Client
 * %%
 * Copyright (C) 2016 SENASA
 * %%
 * This software is the confidential and proprietary information of SENASA. 
 * You shall not disclose such confidential information and shall use it only 
 * in accordance with the terms of the license agreement you entered into with 
 * SENASA.
 * #L%
 */

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * Port that exposes operations on task
 *
 * This class was generated by Apache CXF 3.1.8
 * 2016-11-03T10:59:40.311-05:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService", name = "TaskService")
@XmlSeeAlso({oracle.bpel.services.workflow.evidence.model.ObjectFactory.class, oracle.bpel.services.workflow.task.command.model.ObjectFactory.class, oracle.bpel.services.workflow.metadata.routingslip.model.ObjectFactory.class, oracle.bpel.services.workflow.task.model.ObjectFactory.class, ObjectFactory.class, oracle.bpel.services.workflow.task.error.model.ObjectFactory.class, oracle.bpel.services.workflow.query.model.ObjectFactory.class, oracle.bpel.services.workflow.common.tsc.model.ObjectFactory.class, oracle.bpel.services.workflow.common.model.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TaskService {

    /**
     * Add an document to a task
     */
    @WebMethod
    @WebResult(name = "task", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/task", partName = "payload")
    public oracle.bpel.services.workflow.task.model.Task addDocument(
        @WebParam(partName = "payload", name = "addDocument", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        AddDocumentType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Route a task
     */
    @WebMethod
    @WebResult(name = "task", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/task", partName = "payload")
    public oracle.bpel.services.workflow.task.model.Task routeTask(
        @WebParam(partName = "payload", name = "routeTask", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        RouteTaskType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Escalate a list of tasks
     */
    @WebMethod
    @WebResult(name = "bulkOperationOutput", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService", partName = "payload")
    public boolean escalateTasks(
        @WebParam(partName = "payload", name = "escalateTasks", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        TaskIdsType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Add a comment to a task
     */
    @WebMethod
    @WebResult(name = "task", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/task", partName = "payload")
    public oracle.bpel.services.workflow.task.model.Task addComment(
        @WebParam(partName = "payload", name = "addComment", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        AddCommentType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Reassign a list of tasks
     */
    @WebMethod
    @WebResult(name = "bulkOperationOutput", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService", partName = "payload")
    public boolean reassignTasks(
        @WebParam(partName = "payload", name = "reassignTasks", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        ReassignTasksType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Resume a task
     */
    @WebMethod
    @WebResult(name = "task", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/task", partName = "payload")
    public oracle.bpel.services.workflow.task.model.Task resumeTask(
        @WebParam(partName = "payload", name = "resumeTask", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        TaskServiceContextTaskTaskIdBaseType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Release a task
     */
    @WebMethod
    @WebResult(name = "task", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/task", partName = "payload")
    public oracle.bpel.services.workflow.task.model.Task releaseTask(
        @WebParam(partName = "payload", name = "releaseTask", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        TaskServiceContextTaskTaskIdBaseType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Prepare for restarting an approval task
     */
    @WebMethod
    @WebResult(name = "task", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/task", partName = "payload")
    public oracle.bpel.services.workflow.task.model.Task prepareForRestartRootTask(
        @WebParam(partName = "payload", name = "prepareForRestartRootTask", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        RestartRootTaskType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Re-evaluate task
     */
    @WebMethod
    @WebResult(name = "reevaluateTaskOutput", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService", partName = "payload")
    public boolean reevaluateTask(
        @WebParam(partName = "payload", name = "reevaluateTask", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        ReevaluateTaskType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Delegate a list of tasks
     */
    @WebMethod
    @WebResult(name = "bulkOperationOutput", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService", partName = "payload")
    public boolean delegateTasks(
        @WebParam(partName = "payload", name = "delegateTasks", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        DelegateTasksType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Set Task sequence Changes
     */
    @WebMethod
    @WebResult(name = "setTaskSequenceChangesOutput", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService", partName = "payload")
    public int setTaskSequenceChanges(
        @WebParam(partName = "payload", name = "setTaskSequenceChanges", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        SetTaskSequenceChangesType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Create Todo task
     */
    @WebMethod
    @WebResult(name = "task", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/task", partName = "payload")
    public oracle.bpel.services.workflow.task.model.Task createToDoTask(
        @WebParam(partName = "payload", name = "createToDoTask", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        CreateToDoTaskType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Withdraw a task
     */
    @WebMethod
    @WebResult(name = "task", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/task", partName = "payload")
    public oracle.bpel.services.workflow.task.model.Task withdrawTask(
        @WebParam(partName = "payload", name = "withdrawTask", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        TaskServiceContextTaskTaskIdBaseType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Combine a series of Bulk Operations.
     */
    @WebMethod
    @WebResult(name = "updateTasksByCommandsOutput", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService", partName = "payload")
    public UpdateTasksByCommandsOutputType updateTasksByCommands(
        @WebParam(partName = "payload", name = "updateTasksByCommands", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        UpdateTasksByCommandsType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Add an attachment to a task
     */
    @WebMethod
    @WebResult(name = "task", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/task", partName = "payload")
    public oracle.bpel.services.workflow.task.model.Task addAttachment(
        @WebParam(partName = "payload", name = "addAttachment", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        AddAttachmentType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Reintiate a task
     */
    @WebMethod
    @WebResult(name = "reinitiateTaskResponse", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService", partName = "payload")
    public TaskServiceContextTaskBaseType reinitiateTask(
        @WebParam(partName = "payload", name = "reinitiateTask", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        InitiateTaskType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * PushBack a task
     */
    @WebMethod
    @WebResult(name = "task", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/task", partName = "payload")
    public oracle.bpel.services.workflow.task.model.Task pushBackTask(
        @WebParam(partName = "payload", name = "pushBackTask", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        TaskServiceContextTaskTaskIdBaseType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Error a task
     */
    @WebMethod
    @WebResult(name = "task", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/task", partName = "payload")
    public oracle.bpel.services.workflow.task.model.Task errorTask(
        @WebParam(partName = "payload", name = "errorTask", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        TaskServiceContextTaskTaskIdBaseType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Purge a task
     */
    @WebMethod
    @WebResult(name = "purgeTaskOutput", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService", partName = "payload")
    public boolean purgeTask(
        @WebParam(partName = "payload", name = "purgeTask", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        TaskServiceContextTaskTaskIdBaseType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Merge and update a task
     */
    @WebMethod
    @WebResult(name = "task", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/task", partName = "payload")
    public oracle.bpel.services.workflow.task.model.Task mergeAndUpdateTask(
        @WebParam(partName = "payload", name = "mergeAndUpdateTask", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        TaskServiceContextTaskBaseType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Update a task
     */
    @WebMethod
    @WebResult(name = "task", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/task", partName = "payload")
    public oracle.bpel.services.workflow.task.model.Task updateTask(
        @WebParam(partName = "payload", name = "updateTask", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        TaskServiceContextTaskBaseType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Submit information for a task
     */
    @WebMethod
    @WebResult(name = "task", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/task", partName = "payload")
    public oracle.bpel.services.workflow.task.model.Task submitInfoForTask(
        @WebParam(partName = "payload", name = "submitInfoForTask", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        TaskServiceContextTaskBaseType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Delegate a task
     */
    @WebMethod
    @WebResult(name = "task", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/task", partName = "payload")
    public oracle.bpel.services.workflow.task.model.Task delegateTask(
        @WebParam(partName = "payload", name = "delegateTask", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        DelegateTaskType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Initiate a task
     */
    @WebMethod
    @WebResult(name = "initiateTaskResponse", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService", partName = "payload")
    public TaskServiceContextTaskBaseType initiateTask(
        @WebParam(partName = "payload", name = "initiateTask", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        InitiateTaskType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Suspend a task
     */
    @WebMethod
    @WebResult(name = "task", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/task", partName = "payload")
    public oracle.bpel.services.workflow.task.model.Task suspendTask(
        @WebParam(partName = "payload", name = "suspendTask", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        TaskServiceContextTaskTaskIdBaseType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Acquire a task
     */
    @WebMethod
    @WebResult(name = "task", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/task", partName = "payload")
    public oracle.bpel.services.workflow.task.model.Task acquireTask(
        @WebParam(partName = "payload", name = "acquireTask", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        TaskServiceContextTaskTaskIdBaseType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Update task outcome
     */
    @WebMethod
    @WebResult(name = "task", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/task", partName = "payload")
    public oracle.bpel.services.workflow.task.model.Task updateTaskOutcome(
        @WebParam(partName = "payload", name = "updateTaskOutcome", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        UpdateTaskOutcomeType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Update task outcome and route the task user(s)/group(s)
     */
    @WebMethod
    @WebResult(name = "task", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/task", partName = "payload")
    public oracle.bpel.services.workflow.task.model.Task updateTaskOutcomeAndRoute(
        @WebParam(partName = "payload", name = "updateTaskOutcomeAndRoute", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        UpdateTaskOutcomeAndRouteType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Acquire a set of tasks
     */
    @WebMethod
    @WebResult(name = "bulkOperationOutput", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService", partName = "payload")
    public boolean acquireTasks(
        @WebParam(partName = "payload", name = "acquireTasks", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        TaskIdsType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Request information for task and have the task reapproved by users who approved the task since the user to whom information is requested
     */
    @WebMethod
    @WebResult(name = "task", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/task", partName = "payload")
    public oracle.bpel.services.workflow.task.model.Task requestInfoForTaskWithReapproval(
        @WebParam(partName = "payload", name = "requestInfoForTaskWithReapproval", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        RequestInfoForTaskType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Update the ArchivedOn value of a Task
     */
    @WebMethod
    @WebResult(name = "successResponseOutput", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService", partName = "payload")
    public java.lang.String updateArchivedOnValueForTasks(
        @WebParam(partName = "payload", name = "updateArchivedOnValueForTasks", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        ArchivedOnIdsListType payload
    ) throws WorkflowErrorMessage;

    /**
     * Request information for task
     */
    @WebMethod
    @WebResult(name = "task", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/task", partName = "payload")
    public oracle.bpel.services.workflow.task.model.Task requestInfoForTask(
        @WebParam(partName = "payload", name = "requestInfoForTask", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        RequestInfoForTaskType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Skip current assignment for the task
     */
    @WebMethod
    @WebResult(name = "task", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/task", partName = "payload")
    public oracle.bpel.services.workflow.task.model.Task skipCurrentAssignment(
        @WebParam(partName = "payload", name = "skipCurrentAssignment", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        TaskServiceContextTaskBaseType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Purge a set of tasks
     */
    @WebMethod
    @WebResult(name = "bulkOperationOutput", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService", partName = "payload")
    public boolean purgeTasks(
        @WebParam(partName = "payload", name = "purgeTasks", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        TaskIdsType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Override routing slip for a task
     */
    @WebMethod
    @WebResult(name = "task", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/task", partName = "payload")
    public oracle.bpel.services.workflow.task.model.Task overrideRoutingSlip(
        @WebParam(partName = "payload", name = "overrideRoutingSlip", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        OverrideRoutingSlipType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Update the priority of a Task
     */
    @WebMethod
    @WebResult(name = "successResponseOutput", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService", partName = "payload")
    public java.lang.String updatePriorityOfTasks(
        @WebParam(partName = "payload", name = "updatePriorityOfTasks", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        PriorityIdsListType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Escalate a task
     */
    @WebMethod
    @WebResult(name = "task", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/task", partName = "payload")
    public oracle.bpel.services.workflow.task.model.Task escalateTask(
        @WebParam(partName = "payload", name = "escalateTask", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        TaskServiceContextTaskTaskIdBaseType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Delete a set of tasks
     */
    @WebMethod
    @WebResult(name = "bulkOperationOutput", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService", partName = "payload")
    public boolean deleteTasks(
        @WebParam(partName = "payload", name = "deleteTasks", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        TaskIdsType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Suspend a set of tasks
     */
    @WebMethod
    @WebResult(name = "bulkOperationOutput", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService", partName = "payload")
    public boolean suspendTasks(
        @WebParam(partName = "payload", name = "suspendTasks", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        TaskIdsType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Get future participants of a task
     */
    @WebMethod
    @WebResult(name = "routingSlip", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/routingSlip", partName = "payload")
    public oracle.bpel.services.workflow.metadata.routingslip.model.RoutingSlip getFutureParticipants(
        @WebParam(partName = "payload", name = "getFutureParticipants", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        TaskServiceContextTaskTaskIdBaseType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Suspend timers for a task
     */
    @WebMethod
    @WebResult(name = "successResponseOutput", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService", partName = "payload")
    public java.lang.String suspendTimers(
        @WebParam(partName = "payload", name = "suspendTimers", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        TaskServiceContextTaskTaskIdBaseType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Resume a set of tasks
     */
    @WebMethod
    @WebResult(name = "bulkOperationOutput", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService", partName = "payload")
    public boolean resumeTasks(
        @WebParam(partName = "payload", name = "resumeTasks", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        TaskIdsType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Get users to request information for a task
     */
    @WebMethod
    @WebResult(name = "listOfUserIds", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService", partName = "payload")
    public ListOfUserIdsType getUsersToRequestInfoForTask(
        @WebParam(partName = "payload", name = "getUsersToRequestInfoForTask", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        TaskServiceContextTaskTaskIdBaseType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Release a set of tasks
     */
    @WebMethod
    @WebResult(name = "bulkOperationOutput", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService", partName = "payload")
    public boolean releaseTasks(
        @WebParam(partName = "payload", name = "releaseTasks", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        TaskIdsType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Reassign a task
     */
    @WebMethod
    @WebResult(name = "task", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/task", partName = "payload")
    public oracle.bpel.services.workflow.task.model.Task reassignTask(
        @WebParam(partName = "payload", name = "reassignTask", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        ReassignTaskType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Withdraw a set of tasks
     */
    @WebMethod
    @WebResult(name = "bulkOperationOutput", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService", partName = "payload")
    public boolean withdrawTasks(
        @WebParam(partName = "payload", name = "withdrawTasks", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        TaskIdsType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Delete a task
     */
    @WebMethod
    @WebResult(name = "task", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/task", partName = "payload")
    public oracle.bpel.services.workflow.task.model.Task deleteTask(
        @WebParam(partName = "payload", name = "deleteTask", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        TaskServiceContextTaskTaskIdBaseType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Renew a task
     */
    @WebMethod
    @WebResult(name = "task", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/task", partName = "payload")
    public oracle.bpel.services.workflow.task.model.Task renewTask(
        @WebParam(partName = "payload", name = "renewTask", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        RenewTaskType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Resume timers for a task
     */
    @WebMethod
    @WebResult(name = "successResponseOutput", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService", partName = "payload")
    public java.lang.String resumeTimers(
        @WebParam(partName = "payload", name = "resumeTimers", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        TaskServiceContextTaskTaskIdBaseType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Restart an approval task
     */
    @WebMethod
    @WebResult(name = "initiateTaskResponse", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService", partName = "payload")
    public TaskServiceContextTaskBaseType restartRootTask(
        @WebParam(partName = "payload", name = "restartRootTask", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        RestartRootTaskType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Acquire a set of tasks
     */
    @WebMethod
    @WebResult(name = "bulkOperationOutput", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService", partName = "payload")
    public boolean updateOutcomeOfTasks(
        @WebParam(partName = "payload", name = "updateOutcomeOfTasks", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        UpdateOutcomeOfTasks payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Remove an document to a task
     */
    @WebMethod
    @WebResult(name = "task", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/task", partName = "payload")
    public oracle.bpel.services.workflow.task.model.Task removeDocument(
        @WebParam(partName = "payload", name = "removeDocument", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        RemoveDocumentType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Get all approvers
     */
    @WebMethod
    @WebResult(name = "listOfUserIds", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService", partName = "payload")
    public ListOfUserIdsType getApprovers(
        @WebParam(partName = "payload", name = "getApprovers", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        TaskServiceContextTaskTaskIdBaseType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Add a comment to a list of tasks
     */
    @WebMethod
    @WebResult(name = "bulkOperationOutput", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService", partName = "payload")
    public boolean addCommentToTasks(
        @WebParam(partName = "payload", name = "addCommentToTasks", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        AddCommentToTasks payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Remove an attachment to a task
     */
    @WebMethod
    @WebResult(name = "task", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/task", partName = "payload")
    public oracle.bpel.services.workflow.task.model.Task removeAttachment(
        @WebParam(partName = "payload", name = "removeAttachment", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        RemoveAttachmentType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Add Business task
     */
    @WebMethod
    @WebResult(name = "task", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/task", partName = "payload")
    public oracle.bpel.services.workflow.task.model.Task decomposeTask(
        @WebParam(partName = "payload", name = "decomposeTask", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        DecomposeTaskType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    /**
     * Update the priority of a Task
     */
    @WebMethod
    @WebResult(name = "successResponseOutput", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService", partName = "payload")
    public java.lang.String updatePriority(
        @WebParam(partName = "payload", name = "updatePriority", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        PriorityIdsType payload
    ) throws WorkflowErrorMessage, StaleObjectFaultMessage;

    public void updateTaskOutcome(TaskServiceContextTaskBaseType payload);
}
