package com.oracle.xmlns.bpel.workflow.taskservice;

/*
 * #%L
 * TUPA: Integration: BPM-Client: HW Task Service Client
 * %%
 * Copyright (C) 2016 SENASA
 * %%
 * This software is the confidential and proprietary information of SENASA. 
 * You shall not disclose such confidential information and shall use it only 
 * in accordance with the terms of the license agreement you entered into with 
 * SENASA.
 * #L%
 */

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * Port implemented by the requester to receive callbacks from workflow
 *
 * This class was generated by Apache CXF 3.1.8
 * 2016-11-03T10:59:39.790-05:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService", name = "TaskServiceCallback")
@XmlSeeAlso({oracle.bpel.services.workflow.evidence.model.ObjectFactory.class, oracle.bpel.services.workflow.task.command.model.ObjectFactory.class, oracle.bpel.services.workflow.metadata.routingslip.model.ObjectFactory.class, oracle.bpel.services.workflow.task.model.ObjectFactory.class, ObjectFactory.class, oracle.bpel.services.workflow.task.error.model.ObjectFactory.class, oracle.bpel.services.workflow.query.model.ObjectFactory.class, oracle.bpel.services.workflow.common.tsc.model.ObjectFactory.class, oracle.bpel.services.workflow.common.model.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TaskServiceCallback {

    /**
     * Callback invoked when the task has been assigned
     */
    @WebMethod
    @Oneway
    public void onTaskAssigned(
        @WebParam(partName = "payload", name = "taskAssignedMessage", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        TaskAssignedMessageType payload
    );

    /**
     * Callback invoked when the task has completed, expired, withdrawn or errored
     */
    @WebMethod
    @Oneway
    public void onTaskCompleted(
        @WebParam(partName = "payload", name = "task", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/task")
        oracle.bpel.services.workflow.task.model.Task payload
    );

    /**
     * Callback invoked when the task has been updated
     */
    @WebMethod
    @Oneway
    public void onTaskUpdated(
        @WebParam(partName = "payload", name = "taskUpdatedMessage", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        TaskUpdatedMessageType payload
    );

    /**
     * Callback invoked when a sub task has been updated
     */
    @WebMethod
    @Oneway
    public void onSubTaskUpdated(
        @WebParam(partName = "payload", name = "subTaskUpdatedMessage", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        SubTaskUpdatedMessageType payload
    );

    /**
     * Callback invoked when a stage completes
     */
    @WebMethod
    @Oneway
    public void onStageCompleted(
        @WebParam(partName = "payload", name = "stageCompleteMessage", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
        StageCompleteMessageType payload
    );
}
