
package com.oracle.xmlns.bpel.workflow.taskservice;

/*
 * #%L
 * TUPA: Integration: BPM-Client: HW Task Service Client
 * %%
 * Copyright (C) 2016 SENASA
 * %%
 * This software is the confidential and proprietary information of SENASA. 
 * You shall not disclose such confidential information and shall use it only 
 * in accordance with the terms of the license agreement you entered into with 
 * SENASA.
 * #L%
 */

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-11-03T10:59:40.305-05:00
 * Generated source version: 3.1.8
 */

@WebFault(name = "operationErroredFault", targetNamespace = "http://xmlns.oracle.com/bpel/workflow/taskService")
public class WorkflowErrorMessage extends Exception {
    
    private com.oracle.xmlns.bpel.workflow.taskservice.FaultMessageType operationErroredFault;

    public WorkflowErrorMessage() {
        super();
    }
    
    public WorkflowErrorMessage(String message) {
        super(message);
    }
    
    public WorkflowErrorMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public WorkflowErrorMessage(String message, com.oracle.xmlns.bpel.workflow.taskservice.FaultMessageType operationErroredFault) {
        super(message);
        this.operationErroredFault = operationErroredFault;
    }

    public WorkflowErrorMessage(String message, com.oracle.xmlns.bpel.workflow.taskservice.FaultMessageType operationErroredFault, Throwable cause) {
        super(message, cause);
        this.operationErroredFault = operationErroredFault;
    }

    public com.oracle.xmlns.bpel.workflow.taskservice.FaultMessageType getFaultInfo() {
        return this.operationErroredFault;
    }
}
